### ISSUE TITLE
Moved out colony still copying moved out elements.

### ISSUE THREAD

**Issue by GuillaumeTz** [mattreecebentley/plf_colony#11]
Hello !

I have seen a problem when a colony is moved out and after this colony is copied : it copy the moved out elements.

You can see the problem with this code : 

struct StructTest
{
	StructTest() { }
	StructTest(const StructTest& Rhs) { std::cout << "Copied" << std::endl; }
	StructTest(StructTest&& Rhs) { std::cout << "Moved" << std::endl; }

	StructTest& operator=(const StructTest& Rhs) { std::cout << "copy assigned" << std::endl; }
	StructTest& operator=(StructTest&& Rhs) { std::cout << "move assigned" << std::endl; }
	~StructTest() { std::cout << "destructed" << std::endl; }
};

int main()
{
	plf::colony<StructTest> Colony1;
	Colony1.insert(StructTest());

	std::cout << "Now performing move construction" << std::endl;
	auto Colony2(std::move(Colony1));

	std::cout << "Now performing copy construction with moved out colony" << std::endl;
	auto Colony3(Colony1);

	std::cout << "End" << std::endl;

	int pause;
	std::cin >> pause;
    return 0;
}

The struct StructTest is copied during the last copy construction.

**Comment by mattreecebentley** [comment]
It sounds like you don't understand how std::move works.
Colony 1 is created.
Colony 1 is moved into Colony 2.
Colony 2 is copied into Colony 3.

That's exactly what should happen in *any* valid container, based on your code.

**Comment by GuillaumeTz** [comment]
When you say the Colony2 is copied into Colony3 are you referring to this line : 

auto Colony3(Colony1); ?

When I replace plf::colony by a std::vector, there is no bug and the struct StructTest is not copied. When I say that the struct is not copied I mean that the copy constructor of the StructTest is not called.

This is due to begin_iterator and end_iterator in plf::colony not being reseted and used in the copy constructor (insert(source.begin_iterator, source.end_iterator);)

So resetting begin_iterator and end_iterator fixed the issue I'm facing.

**Comment by mattreecebentley** [comment]
Sorry, I misread - thought you were copying from colony2.
In terms of what colony is doing, this is correct behaviour.
Moving leaves the source container in an undefined-but-destructible state according to the standard. Since first_group and total_number_of_elements are reset, this is what happens.
So not resetting the begin/end iterators is valid.
If you have a use-case where this creates problems, or a reason why this should be changed I'm happy to listen to it. But I would suggest that such use-cases may create problems with other perfectly valid containers as well.
Thanks,
Matt

**Comment by mattreecebentley** [comment]
From here:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3181.html#1374
"moved-from objects can be destroyed and can be the destination of an assignment. Any other use is undefined behavior." However, the text is unclear on 'recommended practice'. Putting a 'clear' command in there for colony is unnecessary in the general case as most moves tend to be from temporaries.

**Comment by GuillaumeTz** [comment]
Yes I read there : "Unless otherwise specified, all standard library objects that have been moved from are placed in a valid but unspecified state. That is, only the functions without preconditions, such as the assignment operator, can be safely used on the object after it was moved from:" http://en.cppreference.com/w/cpp/utility/move

My use case is that I don't want to override the default generated copy constructor of my class (because I don't want to maintain it), but I want to have a filtered copy, so what I'm doing is move out the elements (to temporaries) which I don't want to be copied, then use the default copy constructor, and then move in the elements to restore the state of my class.

I hope we will soon have a way to manage the default code generated by compilers like Herb Stutter wanted : https://www.youtube.com/watch?v=4AfRAVcThyA

**Comment by mattreecebentley** [comment]
Perhaps I'm not understanding your example correctly, but how does that relate to move-construction/assignment of colony itself? That sounds like it relates to moving elements rather than the whole colony.
Also, why aren't you simply copying out individual elements to a new colony, rather than moving out elements you don't want to copy, then doing a copy-construct? Seems very inefficient.

However, I realised last night that the current move-construction/assignment of colony itself will violate the maxim of allowing the assignment operator to work, so I will update colony as per your request regardless.

**Comment by mattreecebentley** [comment]
ps. Same rules will still apply to moving individual elements - you'll have to erase the element in the source container afterwards - just like with any std:: container.

**Comment by mattreecebentley** [comment]
Update: copy-assignment actually works fine post-move for source colony (uses copy-swap/move idiom), so no need to change.

**Comment by mattreecebentley** [comment]
ps. To use a colony for anything other than copy-assignment post-move, use clear() after.

**Comment by GuillaumeTz** [comment]
Okay thanks for the clarifications !

My usage is this one : 
````
struct ExpansiveStructToCopy
{
	ExpansiveStructToCopy() = default;
	ExpansiveStructToCopy(const ExpansiveStructToCopy& Rhs) 
	{ 
		/* some expansive copy */ 
	}

	ExpansiveStructToCopy(ExpansiveStructToCopy&& Rhs) = default;
	ExpansiveStructToCopy& operator=(const ExpansiveStructToCopy& Rhs) = default;
	ExpansiveStructToCopy& operator=(ExpansiveStructToCopy&& Rhs) = default;
	~ExpansiveStructToCopy() = default;
};

struct MyMainObject
{
	plf::colony<ExpansiveStructToCopy> ExpansiveStructsColony;
	float Dummy;
	//many many more members
	// ...

	MyMainObject(const MyMainObject& Rhs) = default;

	//Filtered copy
	void CopyTo(MyMainObject& Target, bool bCopyExpansiveStructs)
	{
		plf::colony<ExpansiveStructToCopy> SavedColony(std::move(ExpansiveStructsColony));

		//don't want to maintain copy constructor so just use the default one 
		Target = *this;		// <= my problem was happening here, the copy constructor of the ExpansiveStructToCopy was being called

		ExpansiveStructsColony = std::move(SavedColony);

		if (bCopyExpansiveStructs)
		{
			Target.ExpansiveStructsColony = ExpansiveStructsColony;
		}
	}
};
````

**Comment by mattreecebentley** [comment]
Okay cool, I think I'm with you now - 
so basically you're swapping with the temporary colony so that you can optionally choose to copy the colony over or not and avoid that cost if not.

I would suggest clearing the source colony after "plf::colony<ExpansiveStructToCopy> SavedColony(std::move(ExpansiveStructsColony));" - that'll return it to a state equivalent to an empty colony. I'll enquire with the rest of the SG14 group as to what they think the default case should be in this context (bare minimum compliance as it stands, or emptying the colony post-move by default).
My reluctance to blank the other variables is simply cost - it's minimal, but there are multiple functions that use colony's move constructor/assignment within colony, and also outside of that there's the case of temporary copies/moves which the compiler will construct, so I'd prefer to avoid it and just say, "if you need it usable post-move, just use clear()". But I'll see what the others say.

**Comment by mattreecebentley** [comment]
Found a way to make it empty without losing speed - committed

**Comment by GuillaumeTz** [comment]
Ah nice !

Thank you very much !

**Comment by mattreecebentley** [comment]
You're welcome! I wouldn't've found the workaround without you informing me, so thanks-
