### ISSUE TITLE
Conversion error with v5.10

### ISSUE THREAD

**Issue by 0x8000-0000** [mattreecebentley/plf_colony#27]
gcc version 8.3.0 (Debian 8.3.0-6) 

plf_colony/plf_colony.h:1448:73: error: conversion from ‘int’ to ‘plf::colony<ftags::Record>::skipfield_type’ {aka ‘short unsigned int’} may change value [-Werror=conversion]
      const skipfield_type new_value = *(new_location.skipfield_pointer) - 1;
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~

**Comment by mattreecebentley** [comment]
Can we just figure out why this is happening for a second - "*(new_location.skipfield_pointer)" is of type skipfield_type, so I'm guessing it's throwing the error because C++ is auto-promoting the type to int due to the arithmetic ("- 1")?
Cause if so there may be a bunch of other places I would need to update in code. But this seems like a weird error, and possibly a GCC bug.

**Comment by 0x8000-0000** [comment]
I think it is the result of an arithmetic operation between short unsigned and int, so the result is promoted to an int. I was just instantiating the colony and adding a couple of objects.

You may want to try adding -Wconversion -Wsign-conversion to the test suite and review the results.

**Comment by mattreecebentley** [comment]
Fixed. makes for ugly code tho'
