### ISSUE TITLE
Request for tag/release

### ISSUE THREAD

**Issue by jgsogo** [mattreecebentley/plf_colony#41]
Hi! This library is being added to ConanCenter: https://github.com/conan-io/conan-center-index/pull/5985/

It would be easier for us if you tag/release a version instead of using the string in the commit. Is it possible, would you consider to tag the existing latest commit as 6.25 version?

Thanks!

**Comment by mattreecebentley** [comment]
Hi, I'm not sure I understand the issue. I don't upload betas, only release versions. Therefore every commit is a release. Does that clarify things?

**Comment by jgsogo** [comment]
Hi. I didn't realize about your development/publishing process, now I see _almost_ every commit is a new release. It is ok as it is, sure.

We are used to libraries that are being developed in GitHub and we prefer if they use the release/tag to mark some commits as actual releases (with changelog and so). We usually ask library authors for these releases before pinning a commit, because that is usually easier to find and track. But, of course, it is the library authors the ones that decide how to publish and make their work available, we just try to make it available for the C++ community.

Thanks for your work! 😃

**Comment by mattreecebentley** [comment]
Thanks,
yes sometimes I mistakenly make a commit of the wrong file etc, in which case I recommit,
but in all other cases each release *should* be a commit - may apologies for when I get it wrong :)

**Comment by Klaim** [comment]
(`build2` package maintainer here)
I just realized I don't even get github notifications from new commits. So it is still hard to track. For example I didn't get notified that you pushed new commits 5 days ago, while my watching is set to "All Activity".

It might still be worth to tag versions even if it's at each commit, at least so people/package-maintainers get notifications.

**Comment by mattreecebentley** [comment]
I might do it for more major releases.
Just had a quick google, this was the most promising solution for that issue:
https://hubnotify.com/

But other suggestions are here:
https://stackoverflow.com/questions/9845655/how-do-i-get-notifications-for-commits-to-a-repository

[EDIT: looks like I'd have to create a new release for every single commit, otherwise people would assume non-release-tagged versions are beta. I don't want to do that. If there are massive problems with either of the solutions above let me know, but otherwise this's just adding busywork and more things I might Forget To Do, which's bad]

**Comment by mattreecebentley** [comment]
Just as a headsup for both of you, 
have removed the plf::rand dependency in the colony and plf::list test suites, replaced with rand().
