### ISSUE TITLE
Support for disabled exceptions

### ISSUE THREAD

**Issue by sunnlok** [mattreecebentley/plf_colony#50]
Right now exceptions are a fixed part of plf_colony, but many projects have exceptions disabled, especially games.
This obviously means that plf_colony will not compile.
I was wondering if there was any interest in supporting users that have disabled exceptions via macros for/around try, catch and throw?
The length_errors could also be handled via asserts in those cases as well.

Was this a deliberate choice or just never considered?
If its deliberate, modifying the source to fit the use case is obviously a valid solution as well, just makes integrating new versions slightly more work.

**Comment by mattreecebentley** [comment]
My understanding is that if exceptions are disabled, then the code will compile, but the compiler will not include the code in the catch blocks, or throw statements. Otherwise games which don't use exceptions wouldn't work with anything that did, including STD:: stuff and OS stuff.
Obviously the upshot of what this means is going to vary from compiler to compiler, as disabling exceptions is outside of  the C++ standard behaviour, see here:
https://stackoverflow.com/questions/943087/what-exactly-will-happen-if-i-disable-c-exceptions-in-a-project
for MSVC and here:
https://stackoverflow.com/questions/45935978/what-happens-when-code-that-throws-exceptions-is-linked-against-a-library-compil
for GCC.

As long as the user doesn't do anything stupid (over-allocate memory, etc) in colony they won't encounter exceptions. If they do, there is no way of handling these with error codes instead as allocator_traits::construct doesn't have a return value, only exceptions, and it is required for allocator support, so malloc etc aren't appropriate.

If you've got a specific compiler/situation where colony is causing problems in this scenario (exceptions turned off) please tell me and I'll look into it.

[UPDATE: okay, compiled with -fno-exceptions under GCC shows me the problem, at least for GCC. Will look into it. GCC has the __EXCEPTIONS flag, possibly clang as well, I think MSVC compiles exceptions code fine when exceptions are disabled, but will have to check]

**Comment by sunnlok** [comment]
Thank you for the quick answer and sorry for not providing more info... Not sure why i forgot that.
Yes the error only seems to appear under gcc/clang.

`cannot use 'try'/'throw with exceptions disabled`
for clang
and
`plf_colony.h:1090:17: error: exception handling disabled, use ���-fexceptions��� to enable   catch (...)`
for gcc
Msvc builds fine on all platforms.

Afaik the stl solves this internally via macros

**Comment by sunnlok** [comment]
Also another issue i have found for vs2017 only:
`plf_colony.h(4169): warning C4996: 'std::allocator<unsigned char>::size_type': warning STL4010: Various members of std::allocator are deprecated in C++17. Use std::allocator_traits instead of accessing these members directly. You can define _SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
 Microsoft Visual Studio Compiler\Tools\include\xmemory0(957): note: see declaration of 'std::allocator<unsigned char>::size_type'
(somefile): note: see reference to class template instantiation 'plf::colony<T,TAllocator,plf::performance>::colony_data' being compiled`

It seems that the constructor for "colony_data" somhow gets confused which size_type to use and pulls it from its base class instead.
Changing it to:
`colony_data(const colony::size_type size)`
seems to solve the issue.

**Comment by mattreecebentley** [comment]
Ah, that's interesting. Okay, will fix.

**Comment by sunnlok** [comment]
Aweseom! Thanks!
Another unrelated issue:
The constructor for colony_data under visual studio 2017 seems to confuse its argument size_type with the one from the allocator it inherits from for... some reason, causing a warning about accessing deprecated members of allocators. The allocator traits define seems to not affect it.
Changing it to colony::size_type seemed to fix it.

**Comment by mattreecebentley** [comment]
Both fixed now, thanks-

**Comment by AIIleG** [comment]
Hi,

compiling with exceptions disabled didn't work for me:

`"plf_colony.h", line 1460: error: support for exception handling is disabled
`

This happens with the github checkout from just a few minutes ago as well as the homepage download from 2 hours ago.

**Comment by AIIleG** [comment]
I had a look and it seems the problem was introduced in https://github.com/mattreecebentley/plf_colony/commit/0acfca7a737129a08d0ebd9a2a83da2866e14ff7

**Comment by mattreecebentley** [comment]
Fixed now, thanks :)
