### ISSUE TITLE
Visit function for blocks as data alternative

### ISSUE THREAD

**Issue by sunnlok** [mattreecebentley/plf_colony#52]
Just out of curiosity:
Is there a specific reason why there is no "visit" function, which takes a lambda/functor with the block pointers as the signature?
I suppose the allocation for the bitfield location would still be required so not much is saved there.

**Comment by mattreecebentley** [comment]
Hey, can't quite understand this, explain it to me like I'm 5?

**Comment by sunnlok** [comment]
something along the lines of:

```cpp
//Function
template<typename Visitor>
void visit_blocks(Visitor&& visitor)
{
//Imagine there is a proper implementation here
for (group_pointer_type current_group = begin_iterator.group_pointer; current_group != end_iterator.group_pointer; current_group = current_group->next_group, ++group_number)
{
visitor(extractPointer, extractBitfield, extractCapacity);
}
}

//User code
auto myVisitor = [&](aligned_pointer_type* const block_pointer, unsigned char* bitfield_pointer, size_t block_size)
{
//Do stuff
}

plf::colony myColony{};

myColony.visit_blocks(myVisitor);
```

Basically a way so blocks/groups can be iterated without requiring an allocation and giving the user more control.

**Comment by mattreecebentley** [comment]
I see a few problems there - problem 1 is that myVisitor has to have access to the aligned_pointer_type,
problem 2 is that myVisitor has to know what skipfield_type the colony is using (will vary based on colony<type> and template priority parameter).
The third and most problematic one is that myVisitor has to know how to iterate over a low-complexity jump-counting skipfield in order to construct it's own bitfield (or to just iterate over the jump-counting skipfield if it chooses not to convert it into a bitfield).
For the first 2 I could make both of those types public, but the third is more problematic, and doubles work on the part of the user which the container already does for them.
Also not clear on what the percieved benefit is.

Currently bitfields are constructed for the user by data(), so those are the main allocations, the rest is just an array of pointers to the existing element blocks.

**Comment by sunnlok** [comment]
I think the main reason for this from my side is to have more control as the user on how to deal with the underlying data.
The current data obviously provides the information but i have no control over how it allocates data or if it allocates data at all, even if the allocated amount isn't all that big.
This most certainly is for "advanced" use cases where you would want to be able to manage "side effects" of an iteration over the blocks yourself.
A way to access the groups directly would also be a solution because then its left up to the user anyways.
In the end i was just curious why this route was chosen to avoid any pitfalls if i decided to modify the implementation locally.

**Comment by mattreecebentley** [comment]
I think it's probably not worth looking at, since the only avoided allocation is the array of pointers to blocks.
You can't reasonably expect most users to construct their own jump-counting iterator, but certainly something people can fork if it's necessary for their use-case.
