### ISSUE TITLE
clear() implementation

### ISSUE THREAD

**Issue by arnaudbrejeon** [mattreecebentley/plf_colony#7]
I've been tempted to use colony instead std::vector because we use structs containing a boolean flag for tagging erased elements.
My problem with colony so far is that memory is deallocated when calling clear(), which is not the case of std::vector. I was wondering if keeping the allocating memory when clear() is called is something you are considering, and forcing the deallocation upon shrink_to_fit

**Comment by mattreecebentley** [comment]
Good point. I think vector does it the right way from a performance perspective. The problem for colony is that it currently doesn't support trailing empty groups (memory blocks +  metadata). I'd like to resolve this as it messes with reserve (which can only reserve up to the maximum group size). Unfortunately I'm not going to have a lot of time to look into it until end-of-year. In the meantime I could change it so it preserves at least the largest group currently allocated, if that's useful. Let me know-

**Comment by arnaudbrejeon** [comment]
I see. No rush on my side. I may look at what how it to do it when I find  some time.

**Comment by mattreecebentley** [comment]
All good I will leave it till end of year= there's a few other things I want to implement as well, but working on plf_list at the moment.

**Comment by arnaudbrejeon** [comment]
I've started thinking about the solution and could be nice to be able provide a memory-management policy as a template for the colony.
What I mean by policy is an external function that decides what to do when a group becomes empty.
Your current policy is to always free empty groups. A vector-like policy would be to keep all allocated groups. We could also think about more complex policies depending on the application use-case (e.g free memory when the occupation is beyond a given threshold).
The policy function would called when a group becomes empty. It would return true to decide to free the group, false to keep it.
I'm not sure about the input parameters yet, probably, the number of groups, the number of empty groups and the total number of elements.
I haven't looked at the code yet, I may have some time this week.

**Comment by mattreecebentley** [comment]
http://www.plflib.org/colony.htm
Please read no. 15 in the FAQ section.

**Comment by arnaudbrejeon** [comment]
I did a first implementation in the following fork: https://github.com/arnaudbrejeon/plf_colony/commits/master

The default behaviour is to free memory as soon as a group is empty like your current behaviour.
There is new template parameter that you can set to false to prevent from releasing memory.

Empty groups are put in a new linked list and are ready for re-use when a new group needs to be created.

One potential problem is that small groups may be kept in the empty groups linked list and never re-used because they are too small. I implemented a simple logic to free them little by little, but it can probably be improved.

I have tested the build only with clang on OSX and all tests look OK with both releasing or re-using memory.

**Comment by mattreecebentley** [comment]
In terms of parameters, how you've done it is how I'll do it - I think greater super-structure stuff (number of elements etc) is out of scope. It makes sense for a fork, but I think as a generalization that sort of thing is better served by the host application comparing size to capacity and deciding whether or not to do a shrink_to_fit or trim_trailing_groups (a necessary function to be added, if trailing groups are to be supported) on it's own terms. 
However, adding the additional linked list is not necessary. Adding to the back of the existing chain is fine. Iterations will quit when they hit end() (or fail if they don't, regardless of whether or not trailing groups are supported).
When I have a chance to implement this, I will mostly:
1. Preserve groups (during erase) only if the group in question is at max possible group size - otherwise you end up losing iteration speed overall as per the FAQ.
2. Add trim_trailing_groups ala my stack replacement.
3. Make the default behaviour of clear() to preserve all groups regardless of size.

Overall I think it's a good idea, and consistent with the focus of the project - before you'd mentioned it, I hadn't thought about clearing the groups and shifting them to the end of the chain. But before that is possible, I have to do a whole heap of work to allow for this functionality, across almost all functions. Otherwise clear and proper reserve aren't going to work too.
Thanks,
Matt

**Comment by arnaudbrejeon** [comment]
Sounds good. I think I'll start using my implementation for now and switch to yours when it is ready.
I'll keep on pushing changes/bug fixes to my fork.

**Comment by mattreecebentley** [comment]
Good - I think that's the best approach. One note though, I realized the parameter probably should be a mutable bool, as if it's a template parameter colony1 = colony2 or colony1 == colony2 (and other functions) will cease to work if each has a different deallocation scheme.

**Comment by arnaudbrejeon** [comment]
Good point.

**Comment by mattreecebentley** [comment]
Implemented this over the weekend in plf::list, basic results are: done right it creates a small performance benefit over not retaining groups, retaining all groups is significantly slower, retaining any groups == max_group_size and == the end group/the one before it seems to create the best performance advantage under high modification benching.

**Comment by arnaudbrejeon** [comment]
Nice!

**Comment by mattreecebentley** [comment]
BTW have been meaning to say we discussed this with SG14 last year, general concensus was that it would probably be better left to an allocator to achieve the same purpose. What are your thoughts?
I did get a version halfway working with this, gave max 2% performance benefit in general usage testing under haswell, gcc (nothing under core2)

**Comment by arnaudbrejeon** [comment]
I would have expected more than 2% performance gain.
I hadn't thought about the allocator solution. This looks very interesting, although I've never implemented an allocator myself.

**Comment by mattreecebentley** [comment]
I suspect the performance increase would be better with a properly
designed allocator, but it's hard to say.

**Comment by mattreecebentley** [comment]
BTW much the same results were observed for plf::list -  I think there was a little more performance gain because the groups sizes are smaller with plf::list so there's more allocations.

**Comment by mattreecebentley** [comment]
I ended up using your suggestion btw - the separate pointer for holding a list of unused groups. I may go back to it merely for the benefit of being able to implement reserve properly-

**Comment by mattreecebentley** [comment]
Tried this again recently - you can find the results here:
plflib.org/blog.htm
Basically, you always end up losing performance.
However, if you'd like the versions of colony with the block retention, I can upload them here.
